 r←Test_Init_07(stopFlag batchFlag);Foo;ref;rc;log;⎕TRAP
⍝ Exercise `Run` with a test function that crashes and asks the user to execute "T.QuitTests". Was `Cleanup_foo` executed?
 ⎕TRAP←(999 'C' '∘∘∘ ⍝ Deliberate error')(0 'N')
 r←T._Failed

 #.⎕SHADOW'Temp'
 'Temp'#.⎕NS''
 #.Temp.I_was_here←0
 #.Temp.T2←⎕NEW ##.Tester2 #.Temp
 #.Temp.⎕FX'r←Initial_foo' '∆Testing←0' 'r←1'
 #.Temp.⎕FX'r←Test_foo_01 x;⎕TRAP' '∘∘∘ ⍝ Now execute T2.QuitTests in the session!'
 #.Temp.⎕FX'Cleanup_foo' '⎕EX ''∆Testing'''
 (rc log)←#.Temp.T2.Run 1
 →T.PassesIf 0=rc
 →T.PassesIf 0=#.Temp.⎕NC'∆Testing'

 r←T._OK
